# vimdoc-ja {{{
[[plugins]]
repo = 'vim-jp/vimdoc-ja'
on_cmd = 'H'
hook_add = "command! -nargs=1 H :execute 'h ' . <q-args> . '@ja'"
# }}}
# vim-denops/denops-shared-server.vim {{{
[[plugins]]
repo = 'vim-denops/denops-shared-server.vim'
on_func = ['denops_shared_server#install', 'denops_shared_server#uninstall']
# }}}
# lualine {{{
#[[plugins]]
#repo = 'nvim-lualine/lualine.nvim'
#if = "!exists('$ime')"
#on_event = 'BufAdd'
#lua_source = '''
#require('lualine').setup {
#  options = {
#    theme = 'antibalus',
#    component_separators = { left = '', right = ''},
#    section_separators = { left = '', right = ''},
#  }
#}
#'''
# }}}
# treesitter {{{
[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter'
merged = 0
on_event = ['BufRead','BufNew']
hook_post_update = 'TSUpdate'
hooks_file = '$HOOKS_DIR/treesitter.lua'

[[plugins]]
repo = 'nvim-treesitter/playground'
on_cmd = ['TSPlaygroundToggle']
hooks_file = '$HOOKS_DIR/treesitter-playground.lua'
# }}}
## fern {{{
#[[plugins]]
#repo = 'lambdalisue/fern.vim'
#on_cmd = 'Fern'
#hooks_file = '$HOOKS_DIR/fern.vim'
#
#[[plugins]]
#repo = 'lambdalisue/fern-git-status.vim'
#on_source = 'fern.vim'
#hook_source = '''
#call fern_git_status#init()
#'''
#
#[[plugins]]
#repo = 'fuzmare/fern-renderer-web-devicons.nvim'
#on_source = 'fern.vim'
#hook_source = '''
#let g:fern#renderer = "nvim-web-devicons"
#let g:fern#renderer#web_devicons#indent_markers = 1
#let g:glyph_palette#palette = v:lua.require'fr-web-icons'.palette()
#'''
#
#[[plugins]]
#repo = 'lambdalisue/glyph-palette.vim'
#on_source = 'fern.vim'
#hook_source = '''
#augroup my-glyph-palette
#  autocmd! *
#  autocmd FileType fern call glyph_palette#apply()
#augroup END
#'''
#
#[[plugins]]
#repo = 'kat0h/fern-preview.vim'
#on_source = 'fern.vim'
#hooks_file = '$HOOKS_DIR/fern-preview.vim'
## }}}
# stevearc/oil.nvim {{{
[[plugins]]
repo = 'stevearc/oil.nvim'
on_cmd = 'Oil'
lua_source = '''
require("oil").setup({
  -- Oil will take over directory buffers (e.g. `vim .` or `:e src/`)
  -- Set to false if you want some other plugin (e.g. netrw) to open when you edit directories.
  default_file_explorer = true,
  -- Id is automatically added at the beginning, and name at the end
  -- See :help oil-columns
  columns = {
    "icon",
    -- "permissions",
    -- "size",
    -- "mtime",
  },
  -- Buffer-local options to use for oil buffers
  buf_options = {
    buflisted = false,
    bufhidden = "hide",
  },
  -- Window-local options to use for oil buffers
  win_options = {
    wrap = false,
    signcolumn = "no",
    cursorcolumn = false,
    foldcolumn = "0",
    spell = false,
    list = false,
    conceallevel = 3,
    concealcursor = "nvic",
  },
  -- Send deleted files to the trash instead of permanently deleting them (:help oil-trash)
  delete_to_trash = false,
  -- Skip the confirmation popup for simple operations (:help oil.skip_confirm_for_simple_edits)
  skip_confirm_for_simple_edits = false,
  -- Selecting a new/moved/renamed file or directory will prompt you to save changes first
  -- (:help prompt_save_on_select_new_entry)
  prompt_save_on_select_new_entry = true,
  -- Oil will automatically delete hidden buffers after this delay
  -- You can set the delay to false to disable cleanup entirely
  -- Note that the cleanup process only starts when none of the oil buffers are currently displayed
  cleanup_delay_ms = 2000,
  lsp_file_methods = {
    -- Enable or disable LSP file operations
    enabled = true,
    -- Time to wait for LSP file operations to complete before skipping
    timeout_ms = 1000,
    -- Set to true to autosave buffers that are updated with LSP willRenameFiles
    -- Set to "unmodified" to only save unmodified buffers
    autosave_changes = false,
  },
  -- Constrain the cursor to the editable parts of the oil buffer
  -- Set to `false` to disable, or "name" to keep it on the file names
  constrain_cursor = "editable",
  -- Set to true to watch the filesystem for changes and reload oil
  watch_for_changes = false,
  -- Keymaps in oil buffer. Can be any value that `vim.keymap.set` accepts OR a table of keymap
  -- options with a `callback` (e.g. { callback = function() ... end, desc = "", mode = "n" })
  -- Additionally, if it is a string that matches "actions.<name>",
  -- it will use the mapping at require("oil.actions").<name>
  -- Set to `false` to remove a keymap
  -- See :help oil-actions for a list of all available actions
  keymaps = {
    ["g?"] = "actions.show_help",
    ["<CR>"] = "actions.select",
    ["<C-s>"] = { "actions.select", opts = { vertical = true }, desc = "Open the entry in a vertical split" },
    ["<C-h>"] = { "actions.select", opts = { horizontal = true }, desc = "Open the entry in a horizontal split" },
    ["<C-t>"] = { "actions.select", opts = { tab = true }, desc = "Open the entry in new tab" },
    ["<C-p>"] = "actions.preview",
    ["<C-c>"] = "actions.close",
    ["<C-l>"] = "actions.refresh",
    ["-"] = "actions.parent",
    ["_"] = "actions.open_cwd",
    ["`"] = "actions.cd",
    ["~"] = { "actions.cd", opts = { scope = "tab" }, desc = ":tcd to the current oil directory" },
    ["gs"] = "actions.change_sort",
    ["gx"] = "actions.open_external",
    ["g."] = "actions.toggle_hidden",
    ["g\\"] = "actions.toggle_trash",
  },
  -- Set to false to disable all of the above keymaps
  use_default_keymaps = true,
  view_options = {
    -- Show files and directories that start with "."
    show_hidden = false,
    -- This function defines what is considered a "hidden" file
    is_hidden_file = function(name, bufnr)
      return vim.startswith(name, ".")
    end,
    -- This function defines what will never be shown, even when `show_hidden` is set
    is_always_hidden = function(name, bufnr)
      return false
    end,
    -- Sort file names in a more intuitive order for humans. Is less performant,
    -- so you may want to set to false if you work with large directories.
    natural_order = true,
    -- Sort file and directory names case insensitive
    case_insensitive = false,
    sort = {
      -- sort order can be "asc" or "desc"
      -- see :help oil-columns to see which columns are sortable
      { "type", "asc" },
      { "name", "asc" },
    },
  },
  -- Extra arguments to pass to SCP when moving/copying files over SSH
  extra_scp_args = {},
  -- EXPERIMENTAL support for performing file operations with git
  git = {
    -- Return true to automatically git add/mv/rm files
    add = function(path)
      return false
    end,
    mv = function(src_path, dest_path)
      return false
    end,
    rm = function(path)
      return false
    end,
  },
  -- Configuration for the floating window in oil.open_float
  float = {
    -- Padding around the floating window
    padding = 2,
    max_width = 0,
    max_height = 0,
    border = "rounded",
    win_options = {
      winblend = 0,
    },
    -- preview_split: Split direction: "auto", "left", "right", "above", "below".
    preview_split = "auto",
    -- This is the config that will be passed to nvim_open_win.
    -- Change values here to customize the layout
    override = function(conf)
      return conf
    end,
  },
  -- Configuration for the actions floating preview window
  preview = {
    -- Width dimensions can be integers or a float between 0 and 1 (e.g. 0.4 for 40%)
    -- min_width and max_width can be a single value or a list of mixed integer/float types.
    -- max_width = {100, 0.8} means "the lesser of 100 columns or 80% of total"
    max_width = 0.9,
    -- min_width = {40, 0.4} means "the greater of 40 columns or 40% of total"
    min_width = { 40, 0.4 },
    -- optionally define an integer/float for the exact width of the preview window
    width = nil,
    -- Height dimensions can be integers or a float between 0 and 1 (e.g. 0.4 for 40%)
    -- min_height and max_height can be a single value or a list of mixed integer/float types.
    -- max_height = {80, 0.9} means "the lesser of 80 columns or 90% of total"
    max_height = 0.9,
    -- min_height = {5, 0.1} means "the greater of 5 columns or 10% of total"
    min_height = { 5, 0.1 },
    -- optionally define an integer/float for the exact height of the preview window
    height = nil,
    border = "rounded",
    win_options = {
      winblend = 0,
    },
    -- Whether the preview window is automatically updated when the cursor is moved
    update_on_cursor_moved = true,
  },
  -- Configuration for the floating progress window
  progress = {
    max_width = 0.9,
    min_width = { 40, 0.4 },
    width = nil,
    max_height = { 10, 0.9 },
    min_height = { 5, 0.1 },
    height = nil,
    border = "rounded",
    minimized_border = "none",
    win_options = {
      winblend = 0,
    },
  },
  -- Configuration for the floating SSH window
  ssh = {
    border = "rounded",
  },
  -- Configuration for the floating keymaps help window
  keymaps_help = {
    border = "rounded",
  },
})
'''
# }}}
# monaqa/smooth-scroll.vim {{{
[[plugins]]
repo = 'monaqa/smooth-scroll.vim'
on_func = 'smooth_scroll#flick'
hook_add = '''
let g:smooth_scroll_interval = 1000.0 / 60
let g:smooth_scroll_no_default_key_mappings = 1

nnoremap <C-d> <Cmd>call smooth_scroll#flick( v:count1 * &scroll     , 15)<CR>
nnoremap <C-u> <Cmd>call smooth_scroll#flick(-v:count1 * &scroll     , 15)<CR>
nnoremap <C-f> <Cmd>call smooth_scroll#flick( v:count1 * winheight(0), 20)<CR>
nnoremap <C-b> <Cmd>call smooth_scroll#flick(-v:count1 * winheight(0), 20)<CR>
vnoremap <C-d> <Cmd>call smooth_scroll#flick( v:count1 * &scroll     , 15)<CR>
vnoremap <C-u> <Cmd>call smooth_scroll#flick(-v:count1 * &scroll     , 15)<CR>
vnoremap <C-f> <Cmd>call smooth_scroll#flick( v:count1 * winheight(0), 20)<CR>
vnoremap <C-b> <Cmd>call smooth_scroll#flick(-v:count1 * winheight(0), 20)<CR>

let g:smooth_scroll_scrollkind = "quadratic"
'''
# }}}
# lexima {{{
# [[plugins]]
# repo = 'cohama/lexima.vim'
# on_event = 'InsertEnter'
# }}}
# sandwich {{{
[[plugins]]
repo = 'machakann/vim-sandwich'
on_map = ['<Plug>(sandwich-', '<Plug>(textobj-sandwich-']
hooks_file = '$HOOKS_DIR/sandwich.vim'
# }}}
# kensaku.vim {{{
[[plugins]]
repo = 'lambdalisue/kensaku.vim'
on_source = ['fuzzy-motion.vim']
# }}}
# fuzzy-motion.vim {{{
[[plugins]]
repo = 'yuki-yano/fuzzy-motion.vim'
on_cmd = ['FuzzyMotion']
hooks_file = '$HOOKS_DIR/fuzzy-motion.vim'
# }}}
# denops-translate {{{
[[plugins]]
repo = 'skanehira/denops-translate.vim'
on_cmd = 'Translate'
hook_source = '''
let g:translate_endpoint = 'https://api-free.deepl.com/v2/translate'
'''
# }}}
# quickrun {{{
[[plugins]]
repo = 'thinca/vim-quickrun'
on_cmd = 'QuickRun'
# }}}
# ccc.nvim {{{
[[plugins]]
repo = 'uga-rosa/ccc.nvim'
on_cmd = 'Ccc'
hooks_file = '$HOOKS_DIR/ccc.lua'
# }}}
# synstack {{{
[[plugins]]
repo = 'dylnmc/synstack.vim'
on_cmd = ['SynAuto', 'SynPopup', '<plug>(SynStack)']
# }}}
# gitsigns {{{
[[plugins]]
repo = 'lewis6991/gitsigns.nvim'
on_event = ['BufRead']
hooks_file = '$HOOKS_DIR/gitsigns.lua'
# }}}
# satelite {{{
#[[plugins]]
#repo = 'lewis6991/satellite.nvim'
#on_event = ['BufRead']
#hooks_file = '$HOOKS_DIR/satelite.lua'
# }}}
# dstein64/nvim-scrollview {{{
[[plugins]]
repo = 'dstein64/nvim-scrollview'
on_event = 'BufRead'
hooks_file = ['$HOOKS_DIR/scrollview.lua', '$HOOKS_DIR/scrollview.vim']
# }}}
# insx {{{
[[plugins]]
repo = 'hrsh7th/nvim-insx'
on_event = 'InsertEnter'
lua_source = '''
require('insx.preset.standard').setup()
'''
# }}}
# matchup {{{
[[plugins]]
repo = 'andymass/vim-matchup'
on_event = 'BufRead'
# }}}
# notify {{{
[[plugins]]
repo = 'rcarriga/nvim-notify'
on_lua = 'notify'
lua_add = '''
vim.notify = function(...)
  vim.notify = require('notify')
end
'''
# }}}
# deol {{{
[[plugins]]
repo = 'Shougo/deol.nvim'
depends = ['ddc.vim']
on_cmd = 'Deol'
on_func = 'deol#start()'
hooks_file = '$HOOKS_DIR/deol.vim'
# }}}
# suda {{{
[[plugins]]
repo = 'lambdalisue/suda.vim'
on_cmd = ['SudaRead', 'SudaWrite']
# }}}
# chrisbra/unicode.vim {{{
[[plugins]]
repo = 'chrisbra/unicode.vim'
on_cmd = ['Digraphs', 'UnicodeSearch', 'UnicodeSearch!', 'UnicodeName', 'UnicodeTable', 'DownloadUnicode', 'UnicodeCache']
# }}}
# lukas-reineke/indent-blankline.nvim {{{
[[plugins]]
repo = 'lukas-reineke/indent-blankline.nvim'
on_event = 'BufRead'
hooks_file = '$HOOKS_DIR/indent-blankline.lua'
# }}}
# shellRaining/hlchunk.nvim {{{
#[[plugins]]
#repo = 'shellRaining/hlchunk.nvim'
#on_event = 'BufRead'
#hooks_file = '$HOOKS_DIR/hlchunk.lua'
# }}}
# Shougo/cmdline.vim {{{
[[plugins]]
repo = 'Shougo/cmdline.vim'
on_func = 'cmdline'
hook_source = '''
call cmdline#set_option(#{
  \   highlight_prompt: 'Statement',
  \   highlight_cursor: 'CmdlineCursor',
  \ })
'''
# }}}
# tyru/capture.vim {{{
[[plugins]]
repo = 'tyru/capture.vim'
on_cmd = 'Capture'
# }}}
# fuzmare/line-bisect.vim {{{
[[plugins]]
repo = 'fuzmare/line-bisect.vim'
on_func = 'line_bisect#start'
hook_add = '''
nnoremap H H<Plug>(H)
nnoremap L L<Plug>(L)
nnoremap <Plug>(H)H zzH
nnoremap <Plug>(L)L zzL
sign define line_bisect_up text=┃ texthl=DiagnosticSignOk
sign define line_bisect_down text=┃ texthl=DiagnosticSignHint
sign define line_bisect_mid text=❯ texthl=Normal
sign define line_bisect_blank text=\  texthl=SignColumn
nnoremap <Plug>(L)H <Cmd>call line_bisect#start('screen')<CR><Plug>(hl_bisect)
nnoremap <Plug>(H)L <Cmd>call line_bisect#start('screen')<CR><Plug>(hl_bisect)
nnoremap <Plug>(hl_bisect)H <Cmd>call line_bisect#up()<CR><Plug>(hl_bisect)
nnoremap <Plug>(hl_bisect)L <Cmd>call line_bisect#down()<CR><Plug>(hl_bisect)
nnoremap <Plug>(H) <Nop>
nnoremap <Plug>(L) <Nop>
'''
# }}}
# junegunn/vim-easy-align {{{
[[plugins]]
repo = 'junegunn/vim-easy-align'
on_map = '<Plug>(EasyAlign)'
hook_add = '''
" Start interactive EasyAlign in visual mode (e.g. vipga)
xmap ga <Plug>(EasyAlign)
" Start interactive EasyAlign for a motion/text object (e.g. gaip)
nmap ga <Plug>(EasyAlign)
'''
# }}}
# thinca/vim-qfreplace {{{
[[plugins]]
repo = 'thinca/vim-qfreplace'
on_event = 'QuickFixCmdPost'
# }}}
# dependency plugins
# nvim-web-devicons {{{
[[plugins]]
repo = 'kyazdani42/nvim-web-devicons'
on_lua = 'nvim-web-devicons'
lua_source = '''
require'nvim-web-devicons'.setup()
'''
# }}}
# nvim-lua/plenary.nvim {{{
[[plugins]]
repo = 'nvim-lua/plenary.nvim'
on_cmd = 'Plenary'
# }}}
# filetype plugins
# vimtex {{{
[[plugins]]
repo = 'lervag/vimtex'
on_ft = ['tex']
hooks_file = '$HOOKS_DIR/vimtex.vim'
# }}}
# tani/vim-glance {{{
[[plugins]]
repo = 'tani/vim-glance'
on_ft = 'markdown'
hook_source = '''
let g:glance#markdown_breaks = v:true
let g:glance#markdown_html = v:true
let g:glance#markdown_linkify = v:true
let g:glance#markdown_plugins = ['https://esm.sh/markdown-it-mathjax3?bundle']
let g:glance#stylesheet = '@import url("https://cdn.jsdelivr.net/npm/basscss@8.1.0/css/basscss.min.css");'
'''
# }}}
# vim: fdm=marker
