#!/bin/bash
cd `dirname $0`
dotfiles=`pwd`
echo $dotfiles
echo $HOME
mkdir -p $HOME/.config
#alacritty
ln -s $dotfiles/.config/alacritty $HOME/.config/alacritty
#fcitx
mkdir -p $HOME/.config/fcitx
ln -s $dotfiles/.config/fcitx/skin $HOME/.config/fcitx/skin
ln -s $dotfiles/.config/fcitx/config $HOME/.config/fcitx/config
ln -s $dotfiles/.config/fcitx/profile $HOME/.config/fcitx/profile
#fish
mkdir -p $HOME/.config/fish/functions
ln -s $dotfiles/.config/fish/functions/fish_greeting.fish $HOME/.config/fish/functions/fish_greeting.fish
ln -s $dotfiles/.config/fish/functions/fish_mode_prompt.fish $HOME/.config/fish/functions/fish_mode_prompt.fish
ln -s $dotfiles/.config/fish/functions/fish_prompt.fish $HOME/.config/fish/functions/fish_prompt.fish
ln -s $dotfiles/.config/fish/config.fish $HOME/.config/fish/config.fish
ln -s $dotfiles/.config/fish/fish_plugins $HOME/.config/fish/fish_plugins
#i3
ln -s $dotfiles/.config/i3 $HOME/.config/i3
ln -s $dotfiles/.config/i3blocks $HOME/.config/i3blocks
#picom
ln -s $dotfiles/.config/picom $HOME/.config/picom
#rofi
ln -s $dotfiles/.config/rofi $HOME/.config/rofi
#sway
ln -s $dotfiles/.config/sway $HOME/.config/sway
#systemd
ln -s $dotfiles/.config/systemd $HOME/.config/systemd
#thefuck
ln -s $dotfiles/.config/thefuck $HOME/.config/thefuck
#vivaldi-settings
ln -s $dotfiles/.config/vivaldi-settings $HOME/.config/vivaldi-settings
#waybar
ln -s $dotfiles/.config/waybar $HOME/.config/waybar
#xfce4-volumed
ln -s $dotfiles/.config/xfce4-volumed $HOME/.config/xfce4-volumed
#xkeysnail
ln -s $dotfiles/.config/xkeysnail $HOME/.config/xkeysnail
#yay
ln -s $dotfiles/.config/yay $HOME/.config/yay
#mozc
mkdir -p $HOME/.mozc
ln -s $dotfiles/.mozc/user_dictionary.db $HOME/.mozc/user_dictionary.db
#asobi
mkdir -p $HOME/asobi
ln -s $dotfiles/asobi/bin $HOME/asobi/bin
#bin
ln -s $dotfiles/bin $HOME/bin
#bash
ln -s $dotfiles/.bashrc $HOME/.bashrc
#zsh
ln -s $dotfiles/.zshrc $HOME/.zshrc
#tmux
ln -s $dotfiles/.tmux.conf $HOME/.tmux.conf
#xprofile,Xresources
ln -s $dotfiles/.xprofile $HOME/.xprofile
ln -s $dotfiles/.Xresources $HOME/.Xresources
