#!/bin/bash
cd `dirname $0`
dotfiles=`pwd`
echo $dotfiles
echo $HOME
mkdir -p $HOME/.config
#alacritty
ln -sf $dotfiles/.config/alacritty $HOME/.config/
#foot
ln -sf $dotfiles/.config/foot $HOME/.config/
#fcitx
#mkdir -p $HOME/.config/fcitx
#ln -sf $dotfiles/.config/fcitx/skin $HOME/.config/fcitx/
#ln -sf $dotfiles/.config/fcitx/config $HOME/.config/fcitx/
#ln -sf $dotfiles/.config/fcitx/profile $HOME/.config/fcitx/
#fish
#mkdir -p $HOME/.config/fish/functions
#ln -sf $dotfiles/.config/fish/functions/fish_greeting.fish $HOME/.config/fish/functions/fish_greeting.fish
#ln -sf $dotfiles/.config/fish/functions/fish_mode_prompt.fish $HOME/.config/fish/functions/fish_mode_prompt.fish
#ln -sf $dotfiles/.config/fish/functions/fish_prompt.fish $HOME/.config/fish/functions/fish_prompt.fish
#ln -sf $dotfiles/.config/fish/config.fish $HOME/.config/fish/config.fish
#ln -sf $dotfiles/.config/fish/fish_plugins $HOME/.config/fish/fish_plugins
#i3
ln -sf $dotfiles/.config/i3 $HOME/.config/
ln -sf $dotfiles/.config/i3blocks $HOME/.config/
#neovim
ln -sf $dotfiles/.config/nvim $HOME/.config/
#picom
ln -sf $dotfiles/.config/picom $HOME/.config/
#rofi
ln -sf $dotfiles/.config/rofi $HOME/.config/
#sway
ln -sf $dotfiles/.config/sway $HOME/.config/
#systemd
ln -sf $dotfiles/.config/systemd $HOME/.config/
#thefuck
#ln -sf $dotfiles/.config/thefuck $HOME/.config/
#vivaldi-settings
ln -sf $dotfiles/.config/vivaldi-settings $HOME/.config/
#waybar
ln -sf $dotfiles/.config/waybar $HOME/.config/
#xfce4-volumed
ln -sf $dotfiles/.config/xfce4-volumed $HOME/.config/
#xkeysnail
#ln -sf $dotfiles/.config/xkeysnail $HOME/.config/
#xremap
ln -sf $dotfiles/.config/xremap $HOME/.config/
#yay
#ln -sf $dotfiles/.config/yay $HOME/.config/
#mozc
#mkdir -p $HOME/.mozc
#ln -sf $dotfiles/.mozc/user_dictionary.db $HOME/.mozc/user_dictionary.db
#asobi
mkdir -p $HOME/asobi
ln -sf $dotfiles/asobi/bin $HOME/asobi/
#bin
ln -sf $dotfiles/bin $HOME/
#bash
ln -sf $dotfiles/.bashrc $HOME/.bashrc
#zsh
ln -sf $dotfiles/.config/zsh $HOME/.config/
ln -sf $HOME/.config/zsh/.zshrc $HOME/.zshrc
#tmux
ln -sf $dotfiles/.tmux.conf $HOME/.tmux.conf
#xprofile,Xresources
ln -sf $dotfiles/.xprofile $HOME/.xprofile
#ln -sf $dotfiles/.Xresources $HOME/.Xresources
