snippets:
  # snippet and keyword abbrev
  - name: git status
    keyword: gs
    snippet: git status --short --branch
  # snippet with placeholder
  - name: git commit message
    keyword: gcim
    snippet: git commit -m '{{commit_message}}'
  - name: "null"
    keyword: "null"
    snippet: ">/dev/null 2>&1"
    # auto expand condition
    # If not defined, it is only valid at the beginning of a line.
    context:
      # buffer: '' 
      lbuffer: '.+\s'
      # rbuffer: ''
  - name: branch
    keyword: B
    snippet: git symbolic-ref --short HEAD
    context:
      lbuffer: '^git\s+checkout\s+'
    evaluate: true # eval snippet
  - name: expand ls to exa
    keyword: ls
    snippet: exa
  - name: install package by yay
    keyword: inst
    snippet: yay -S
  - name: remove package by yay
    keyword: unst
    snippet: yay -Rns
  - name: remove no longer needed
    keyword: autoremove
    snippet: sudo sh -c 'pacman -Qdtq | pacman -Rs -'
  - name: expand :q to exit
    keyword: :q
    snippet: exit

completions:
  - name: kill
    patterns: 
      - "^kill( -9)? $"
    sourceCommand: "ps -ef | sed 1d"
    options:
      --multi: true
      --prompt: "'Kill Process> '"
    callback: "awk '{print $2}'"
