# dein {{{
[[plugins]]
repo = 'Shougo/dein.vim'
# }}}

# denops {{{
[[plugins]]
repo = 'vim-denops/denops.vim'
# }}}

# lualine {{{
# [[plugins]]
# repo = 'nvim-lualine/lualine.nvim'
# lua_add = '''
# require('lualine').setup {
#   options = {
#     theme = 'antibalus',
#     component_separators = { left = ' ', right = ' '},
#     section_separators = { left = ' ', right = ' '},
#   }
# }
# '''
# }}}

# FixCursorHold {{{
[[plugins]]
repo = 'antoinemadec/FixCursorHold.nvim'
hook_add = '''
let g:cursorhold_updatetime = 100
'''
# }}}

# gruvbox-material {{{
[[plugins]]
repo = 'sainnhe/gruvbox-material'
on_event = 'UIEnter'
hook_source = '''
let g:gruvbox_material_better_performance = 1
colorscheme gruvbox-material
'''
# }}}

# vim: fdm=marker
