[[plugins]]
repo = 'vim-jp/vimdoc-ja'
on_cmd = ['h','help']
hook_post_source = 'set helplang=ja'

[[plugins]]
repo = 'lervag/vimtex'
on_ft = ['tex']
hook_source = '''
let g:vimtex_compiler_latexmk = {
  \'background': 1,
  \'build_dir': '',
  \'continuous': 1,
  \'options': [
    \'-pdfdvi', 
    \'-verbose',
    \'-file-line-error',
    \'-synctex=1',
    \'-interaction=nonstopmode',
  \],
  \}
let g:vimtex_compiler_progname = 'nvr'
let g:vimtex_view_general_viewer = 'zathura'
let g:vimtex_view_general_options = "-x \"nvr +%{line} %{input}\" --synctex-forward @line:0:@tex @pdf"
'''

[[plugins]]
repo = 'skanehira/preview-markdown.vim'
on_ft = ['markdown']
hook_source = '''
let g:preview_markdown_auto_update = 1
'''

[[plugins]]
repo = 'norcalli/nvim-colorizer.lua'
on_cmd = ['ColorizerAttachToBuffer']
hook_source = '''
lua require 'colorizer'.setup()
'''

[[plugins]]
repo = 'nvim-treesitter/playground'
on_cmd = ['TSPlaygroundToggle']
hook_source = '''
lua << EOF
require "nvim-treesitter.configs".setup {
  playground = {
    enable = true,
    disable = {},
    updatetime = 25, -- Debounced time for highlighting nodes in the playground from source code
    persist_queries = false, -- Whether the query persists across vim sessions
    keybindings = {
      toggle_query_editor = 'o',
      toggle_hl_groups = 'i',
      toggle_injected_languages = 't',
      toggle_anonymous_nodes = 'a',
      toggle_language_display = 'I',
      focus_language = 'f',
      unfocus_language = 'F',
      update = 'R',
      goto_node = '<cr>',
      show_help = '?',
    },
  }
}
EOF
function! s:TSHighlightEnableAuto()
    augroup TSAuto
        autocmd!
        autocmd CursorMoved * execute "TSHighlightCapturesUnderCursor"
    augroup end
endfunction
command! -nargs=0 -bar TSAuto call s:TSHighlightEnableAuto()
'''
