virtual_modifiers:
  - CapsLock
modmap:
  - name: Global
    remap:
      KATAKANAHIRAGANA: ENTER
      CAPSLOCK:
        held: CAPSLOCK
        alone: ESC
        alone_timeout_millis: 200
      HENKAN:
        held: LEFTSHIFT
        alone: HENKAN
        alone_timeout_millis: 200
      MUHENKAN:
        held: LEFTCTRL
        alone: MUHENKAN
        alone_timeout_millis: 200
      SEMICOLON:
        held: LEFTMETA
        alone: SEMICOLON
        alone_timeout_millis: 200

keymap:
  - name: Global
    remap:
      CapsLock-h: LEFT
      CapsLock-j: DOWN
      CapsLock-k: UP
      CapsLock-l: RIGHT
      CapsLock-D: BACKSPACE
      CapsLock-A: HOME
      CapsLock-E: END
