# Dein
[[plugins]]
repo = 'Shougo/dein.vim'

# lightline
[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
	let g:lightline = {'colorscheme': 'popice'}
'''

# Toml
[[plugins]]
repo  = 'cespare/vim-toml'

# coc
[[plugins]]
repo = "neoclide/coc.nvim"
merge = 0
rev = "release"

# Dark Power
[[plugins]]
repo = "Shougo/defx.nvim"
depends = ["defx-git"]
hook_add = """
source ~/.config/nvim/rc/defx.rc.vim
"""
[[plugins]]
repo = "ryanoasis/vim-devicons"
[[plugins]]
repo = "kristijanhusak/defx-icons"
[[plugins]]
repo ="kristijanhusak/defx-git"

[[plugins]]
repo = "Shougo/denite.nvim"
hook_add = """
source ~/.config/nvim/rc/denite.rc.vim
"""

[[plugins]]
repo = "Shougo/deol.nvim"
hook_add = """
source ~/.config/nvim/rc/deol.rc.vim
"""
